<?php


/**
 * Skeleton subclass for representing a row from the 'cre8_mailing_list' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * czw, 11 mar 2010, 11:50:41
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8PropelMailingListPlugin.lib.model
 */
class cre8MailingList extends Basecre8MailingList {

} // cre8MailingList
